### ISSUE TITLE
copyright feedback from SE

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#25]
Here is the feedback from SE on the copyright:
"Hi

you must publish your project under Gnu Public License 2 or later.

I thought that was obvious from the license conditions in each of the Swiss Ephemeris source files, which say

> If the developer choses the GNU GPL software license, he or she must fulfill
>   the conditions of that license, which includes the obligation to place his
>   or her whole software project under the GNU GPL or a compatible license.
>   See http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
"

**Comment by rstub** [comment]
That part is clear: The whole software project must be under GNU GPL *or a compatible license*. In our case that is AGPL, which is like the GPL but with the added restriction that you also have to provide source code when you use the software project only to offer a web service or similar. So that is covered. 

I think I will simply prepare the changes as discussed, i.e. add "Authors of the Swiss Ephemeris" to the "Authors" field and their LICENSE file to the package ...

**Comment by vreijs** [comment]
Agree.

> I think I will simply prepare the changes as discussed, i.e. add "Authors
> of the Swiss Ephemeris" to the "Authors" field and their LICENSE file to
> the package ...
>

**Comment by rstub** [comment]
This has been incorporated in 62b9d1351a840e178c433a8b59e81cfcec12888a.
