### ISSUE TITLE
can I just push my code?

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#5]
Hello Ralf, If I make changes and they don't work... Should I still push it to GitHub?

I tried to add the function:
I put this in swephapi.h:
void swe_set_ephe_path(char file);

and I put this in swephR.cpp:
//' Set the directory for the sefstar.txt and jpl files
//' @param file  the directory plus file (char)
//' @export
// [[Rcpp::export]]
 void set_ephe_path(char file) {
  swe_set_ephe_path(file);
}

compile (all ok) and want to use it with: set_ephe_path("C:\\ARCHAEOCOSMO\\ephe")

R crashes... (C:\ARCHAEOCOSMO\ephe is a valid directory on my system). Any advice how to learn C (aka C for beginners)?

All the best,

Victor

P.S. By the way I get an warning:
"In file included from swephR.cpp:2:0:
swephapi.h:10:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long int64;
              ^"
I think it be simply one(1) 'long' in swephapi.h, but I might misunderstand (I see 'long long' also in the original file)

**Comment by rstub** [comment]
If you create a fork and then use a branches, then I would sa it is a good idea to push even if it is not working correctly. Simply because it would make it easier for me to see what you are doing. Have a look at https://gist.github.com/Chaser324/ce0505fbed06b947d962 for how such a workflow might look.

As for the crash: Keep in mind that `char` in C and C++ is just a single charcter. In order to represent a string, you need an array of `char`, which is sort of equivalent to a pointer to `char`, i.e. `char* `. That is also what the SE function wants. For Rcpp we have to use`std::string`, though. Conversion between the two is an ugly thing, but something like this should work:

    void set_ephe_path(std::string path) {
      swe_set_ephe_path(&path[0]);
    } 

The warning is interesting. It should go away with my latest push, since I have switched to C++11 for other reasons.

**Comment by vreijs** [comment]
Ok I made a fork, so that is now in my own GitHub account:
https://github.com/vreijs/swephR-1
Need to further get experience with how to keep in pace with the uptsream, etc. 

The set_ephe_path works now. I am not able to check it yet, but need e.g. the following function working:
Private Declare Function swe_fixstar Lib "C:\ARCHAEOCOSMO\AddIns\swedll32.dll" _
        Alias "_swe_fixstar@24" ( _
          ByVal Star As String, _
          ByVal tjd As Double, _
          ByVal iflag As Long, _
          ByRef X As Double, _
          ByVal serr As String _
        ) As Long       ' x must be first of six array elements
                        ' serr must be able to hold 256 bytes
                        ' Star must be able to hold 40 bytes

Then I can see if the sefstar.txt is being read in the correct path/filde.

All the best,

Victor

**Comment by rstub** [comment]
This issue seems to be no longer relevant.
