### ISSUE TITLE
Naming of the functions

### ISSUE THREAD

**Issue by vreijs** [rstub/swephR#6]
Hello Ralf, I have been thinking about the naming of the external functions. Perhaps we should add 'swephR_'. Just to make sure that conflict of names not less likely. What do you think?

All the best,

Victor

**Comment by rstub** [comment]
Naming is always hard. Technically all functions live in the `swephR` namespace already, i.e. the full name would be `swephR::day_of_week()` etc. That is also the form that one would use from another package. But if somebody loads the package with `library(swephR)`, than the functions are available without any prefix. And some names are pretty generic (`version()` or `calc()` if we follow along). I am not sure yet what to do.

**Comment by vreijs** [comment]
I think people will use library("swephR"), or not? Indeed there are very common names (version, calc), but perhaps by adding this 'swephR_'. thus the common one are also more unique swephR_version and swephR_calc.
Of course then sephR::swephR_version is quite verbose;-)

**Comment by rstub** [comment]
In addition, `swephR_version` would be missleading, since it is not the version of `swephR` but the SE version. Maybe is makes more sense to name *that* function `swiss_ephemeris_version`. It is *very* verbose, but at least correct. 

This brings me to an important question: What sort of functions/API do we want to offer? Just the same as provided by SE? Or do we want to enrich this for usage from R? After all, R is (also) an interactive language with different constraints and possibilities than C. Some examples:

* There are two functions `swe_get_tid_acc` and `swe_set_tid_acc` in the C API. Currently we are offering them as is to the user. Within R the more typical interface would be *one* function (say `tidal_acceleration`) which accepts a double (possibly NULL) and always returns the current tidal acceleration. With a non-NULL argument, the tidal acceleration will first be set to this value.

* There are two function `swe_calc`and `swe_calc_ut` with identical signature that only differ in the interpretation of the time argument. In R it would be more natural to have one function with an optional argument, e.g. `utc = TRUE`. Without this argument or with an explicit `utc = TRUE`,  `swe_calc_ut` would be called. With `utc = FALSE`, it would be `swe_calc`.

* Again `swe_calc`and `swe_calc_ut`: Via `iflag` they offer different computations which return quite different things. It might make sense to offer different functions at the R level for the different coordinate systems.

...

At this point I can offer R experience, but I am definitely lacking domain knowledge. If we want to offer a richer R interface (which I think would be a good idea), it would be great if you could add some "user stories" as issues. They don't need to be long. Just describe how a typical user would interact with the system.

For example: 

User supplies a list of planets/objects/... and a time stamp. User gets a data.frame with apparent positions in [units] as result.

What do you think?

**Comment by vreijs** [comment]
We could also keep the original function calls 'swe_version' for the user and then use 'internal' rcpp function 'rswe_version'. Only for the version function you could say it is not 'rswe_version' but for all SE function you can, so I don't know if only for this single function to make an expection for the Rcpp calls...
Keep the external functions as in the SE document is also handy...

So as you understand I want to keep things as close as possible. If people want more logical functions they can make a wrapper (that is what I did in my ARCHAEOCOSMO functions by the way). For instance I have a function ObjectLoc, which gives the location of star or planet.

By the way I don't mostly use the '_ut' function as I want to manipulate the DeltaT (which is one of the most unknown thing sin astronomy certain for pre-historic times). For isntance to determine the difference between et and ut one need to manipulate DeltaT. IN that way one can determine the change in DeltaT over the ages  (by using historic solar/lunar eclipse). 
SE is being developed by astrologers, so how they use it I don't know (and I am not interested being an archaeo-astronomer), but I use their accurate ephemeris.

So I would propose to use as much as possible their functions and then we can make more logical functions as a second step. The only one that we can incorporate is the vector idea, IMHO  (I showed how I do it in my ARCHAEOCOSMO package and I saw how you did it  in C/Rcpp). This vector idea does not influence the general SE documentations really;-)

**Comment by vreijs** [comment]
As we need to decide asap on the final naming (the longer we wait the more work...). I propose to do a replace first of 'swe_' into 'rswe_' for internal functions and then add to user oriented functions 'swe_'. Let me know what you think?

**Comment by vreijs** [comment]
This won't work of course!!! As the cpp names link to the C code which start with 'swe_'.
So I think we should call the user faced function 'rswe_' I think that will be only "wrong" for the version function.., So be it.
I checked if this is indeed possible, And i included it in my fork... And it looks to work.

**Comment by rstub** [comment]
I have an alternative suggestion: I really don't like mimicking a C API in R. That is not the way R is supposed to be used. However, I can understand that this might be useful for experts that are familiar with the C API. My suggestion would be to use the naming as we have it now, i.e. stripping the leading `swe_`, but not export these functions, i.e. remove the `//' @export`. Net effect:

* The casual user that only does `library(swephR)` does not get lots of generically named functions. Only those that are particularly designed to be used by an end-user.

* The expert user can still call these functions with `swephR:::version()` etc., where the package name plus tripple colon is mandatory.

Of course, swephR will need some sort of documentation which internal functions are considered save for such usage.

**Comment by vreijs** [comment]
Remember that all functions that I (a user) at least use in ARCHAEOCOSMO 
[SE-ARCHAEOCOSMO.txt](https://github.com/rstub/swephR/files/2280858/SE-ARCHAEOCOSMO.txt)
are user functions, so incl. version(). 
The only ones that are not important for the R-user are the internal Rccpp calls names, as they are just needed for the wrapper (which now start with 'swe_'). So I see the stuff we now make in R just as a wrapper. The real usage of these functions should be in another package (sucha skyscapeR or ARCHAEOCOSMO)...
So all the functions that are in for instance attached, ARCHAEOCOSMO, VBA or Fortran function call overview are user functions for SE.
[SwissEphem207_20180607.vba.txt](https://github.com/rstub/swephR/files/2280856/SwissEphem207_20180607.vba.txt)
These are also described in: 
[swephprg.pdf](https://github.com/rstub/swephR/files/2280861/swephprg.pdf)

Remember I have exiting functions (and their calls to sweph functions) that I don't want to change too much (to reduce my testing time)..

All the best,

Victor


[swissdelphi.pas.txt](https://github.com/rstub/swephR/files/2280857/swissdelphi.pas.txt)

**Comment by vreijs** [comment]
Perhaps I don't really care too much if 'swephR:::' will lead to the functions that are as close as possible to the C API. If if that satisfies you, no problem. But I prefer to have the same function calls as in C (and then use e.g. swephR:::version() or swephR::set-:tid_acc() ). I really don't want to change my own (transcribed VBA) code too much. A lot of hours went into them... 

All the best,

Victor

**Comment by rstub** [comment]
Please note that I consider you as an expert user. Anyway, there is one other possibility: Rcpp allows for renaming the function at the R level. So we could do the following:

* Name the C++ functions whatever we like, e.g. like now stripping the `swe_`.
* Use e.g. `// [[Rcpp::export(swe_version)]]` so that the function is available as `swe_version()` for the user.
* I will make sure that these functions are documented as "expert interface".

Please note that there will always be one difference w.r.t. to the C API: R does not really support call by reference, so for example `swe_calc` at the R level will take only date(time), body number and (optional) flags as arguments. The return value could be a list with the return code of the function call, the double array with positions and speeds and the error message. This would be independent of whether these functions are exported or not.

**Comment by vreijs** [comment]
I think the problem is that at this very moment there are only expert users fro swiss ephemeris (they are all application developers). It would indeed be nice if we could change that (but I doubt that R can do that, it is also quite an expert environment, IMHO).

I think I like your 3 bullets, can you implement that, so I can have a look? Perhaps only for one function (if it is a lot of work)?

Indeed that was my very original query, but I now understnad that R does not support by reference (and it can't be simply emulated)... A pity, I was thinking perhaps in returning then a data-frame (with using the 'original' names in the data frame)? What do you think?

All the best,

Victor

**Comment by rstub** [comment]
Ok. I have done the above and implemented `swe_calc`. Let me know if this works for you.

**Comment by vreijs** [comment]
That works excellent! For instance the results are:
> swe_set_topo(0,50,10)
> swe_set_ephe_path("c:\\ARCHAEOCOSMO\\ephe")
> swe_calc(1234567,0,34818)
$`rc`
[1] 34820
$xx
[1] 293.2899122 -22.1022286   0.9923157   0.0000000   0.0000000   0.0000000
$serr
[1] "SwissEph file 'seplm18.se1' not found in PATH 'c:\\ARCHAEOCOSMO\\ephe\\' \nusing Moshier eph.; "
> 

And this is the same as I get with my ARCHOAECOSMO function: ObjectLoc in Excel. So it works. I think the data frame also is ok, IMHO. You call the original return 'rc', but perhaps we could call it 'return': so we can understand the semantics and similar for other functions.
I will see tomorrow if I can now make the fixstar function! Might be a good test for me.

Great progress! Thanks.
